import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Testing deep linking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.centsser}>
        <a
          href="myapp://gizmos/about"
          className={styles.linkstyle}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2>Open app home screen</h2>
        </a>
        <a
          href="myapp://gizmos/about"
          className={styles.linkstyle}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2>Open app about screen</h2>
        </a>
      </div>
    </>
  );
}
